spring:
  application:
    name: spring-boot-boilerplate

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password: 1234

  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: create
        format_sql: true
    generate-ddl: true

security:
  jwt:
    key: nuVFB5ftldMZpKvVEWAiJX8hKk+goqP2gcjOKWJXpyU=
    expirationMs: 3600000
  encryption:
    salt: 5c0744940b5c369b

